---
- name: 'Ensure Keycloak Client applications'
  community.general.keycloak_client:
    auth_keycloak_url: 'http://localhost:8080'
    auth_username: "{{ keycloak_admin_username }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: 'master'
    name: "{{ client['name'] }}"
    client_id: "{{ client['name'] }}"
    admin_url: "{{ client['admin_url'] | default(omit) }}"
    always_display_in_console: "{{ client['always_display_in_console'] | default(omit) }}"
    attributes: "{{ client['attributes'] | default(omit) }}"
    authentication_flow_binding_overrides: "{{ client['authentication_flow_binding_overrides'] | default(omit) }}"
    authorization_services_enabled: "{{ client['authorization_services_enabled'] | default(omit) }}"
    authorization_settings: "{{ client['authorization_settings'] | default(omit) }}"
    base_url: "{{ client['base_url'] | default(omit) }}"
    bearer_only: "{{ client['bearer_only'] | default(omit) }}"
    client_authenticator_type: "{{ client['client_authenticator_type'] | default(omit) }}"
    client_template: "{{ client['client_template'] | default(omit) }}"
    consent_required: "{{ client['consent_required'] | default(omit) }}"
    default_client_scopes: "{{ client['default_client_scopes'] | default(omit) }}"
    default_roles: "{{ client['default_roles'] | default(omit) }}"
    description: "Ansible Managed - {{ client['description'] | default(omit) }}"
    direct_access_grants_enabled: "{{ client['direct_access_grants_enabled'] | default(omit) }}"
    enabled: "{{ client['enabled'] | default(true) }}"
    frontchannel_logout: "{{ client['frontchannel_logout'] | default(omit) }}"
    full_scope_allowed: "{{ client['full_scope_allowed'] | default(omit) }}"
    implicit_flow_enabled: "{{ client['implicit_flow_enabled'] | default(omit) }}"
    node_re_registration_timeout: "{{ client['node_re_registration_timeout'] | default(omit) }}"
    not_before: "{{ client['not_before'] | default(omit) }}"
    optional_client_scopes: "{{ client['optional_client_scopes'] | default(omit) }}"
    protocol: "{{ client['protocol'] | default(omit) }}"
    protocol_mappers: "{{ client['protocol_mappers'] | default(omit) }}"
    public_client: "{{ client['public_client'] | default(omit) }}"
    realm: "{{ client['realm'] }}"
    redirect_uris: "{{ client['redirect_uris'] | default(omit) }}"
    registered_nodes: "{{ client['registered_nodes'] | default(omit) }}"
    registration_access_token: "{{ client['registration_access_token'] | default(omit) }}"
    root_url: "{{ client['root_url'] | default(omit) }}"
    secret: "{{ client['secret'] | default(omit) }}"
    service_accounts_enabled: "{{ client['service_accounts_enabled'] | default(omit) }}"
    standard_flow_enabled: "{{ client['standard_flow_enabled'] | default(omit) }}"
    surrogate_auth_required: "{{ client['surrogate_auth_required'] | default(omit) }}"
    use_template_config: "{{ client['use_template_config'] | default(omit) }}"
    use_template_mappers: "{{ client['use_template_mappers'] | default(omit) }}"
    use_template_scope: "{{ client['use_template_scope'] | default(omit) }}"
    web_origins: "{{ client['web_origins'] | default(omit) }}"
    state: "{{ client['state'] | default('present') }}"
  loop: "{{ keycloak_clients }}"
  loop_control:
    loop_var: 'client'
    label: "{{ client['name'] }}"
