---
- name: 'Include OS specific vars'
  ansible.builtin.include_vars: "{{ lookup('first_found', role_vars_files) }}"
  vars:
    role_vars_files:
      files:
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
      paths:
        - 'vars'

- name: 'Ensure Keycloak installed'
  ansible.builtin.include_tasks: "tasks/install_{{ keycloak_install_method }}.yml"

- name: 'Ensure Keycloak reverse proxy configured'
  ansible.builtin.include_tasks: 'tasks/install_reverse_proxy.yml'

- name: 'Flush handlers'
  ansible.builtin.meta: 'flush_handlers'

- name: 'Wait for Keycloak to start'
  ansible.builtin.uri:
    url: 'http://localhost:9000/health'
    return_content: true
  register: 'keycloak_health'
  until:
    - keycloak_health['json']['status'] is defined
    - keycloak_health['json']['status'] == 'UP'
  retries: 60
  delay: 2

- name: 'Configure realms'
  ansible.builtin.include_tasks: 'tasks/realms_federation.yml'
