---
- name: 'Configure realms'
  community.general.keycloak_realm:
    auth_keycloak_url: 'http://localhost:8080'
    auth_username: "{{ keycloak_admin_username }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: 'master'
    realm: "{{ realm['name'] }}"
    access_code_lifespan: "{{ realm['access_code_lifespan'] | default(omit) }}"
    access_code_lifespan_login: "{{ realm['access_code_lifespan_login'] | default(omit) }}"
    access_code_lifespan_user_action: "{{ realm['access_code_lifespan_user_action'] | default(omit) }}"
    access_token_lifespan: "{{ realm['access_token_lifespan'] | default(omit) }}"
    access_token_lifespan_for_implicit_flow: "{{ realm['access_token_lifespan_for_implicit_flow'] | default(omit) }}"
    account_theme: "{{ realm['account_theme'] | default(omit) }}"
    action_token_generated_by_admin_lifespan: "{{ realm['action_token_generated_by_admin_lifespan'] | default(omit) }}"
    action_token_generated_by_user_lifespan: "{{ realm['action_token_generated_by_user_lifespan'] | default(omit) }}"
    admin_events_details_enabled: "{{ realm['admin_events_details_enabled'] | default(omit) }}"
    admin_events_enabled: "{{ realm['admin_events_enabled'] | default(omit) }}"
    admin_theme: "{{ realm['admin_theme'] | default(omit) }}"
    attributes: "{{ realm['attributes'] | default(omit) }}"
    browser_flow: "{{ realm['browser_flow'] | default(omit) }}"
    browser_security_headers: "{{ realm['browser_security_headers'] | default(omit) }}"
    brute_force_protected: "{{ realm['brute_force_protected'] | default(omit) }}"
    client_authentication_flow: "{{ realm['client_authentication_flow'] | default(omit) }}"
    client_scope_mappings: "{{ realm['client_scope_mappings'] | default(omit) }}"
    default_default_client_scopes: "{{ realm['default_default_client_scopes'] | default(omit) }}"
    default_groups: "{{ realm['default_groups'] | default(omit) }}"
    default_locale: "{{ realm['default_locale'] | default(omit) }}"
    default_optional_client_scopes: "{{ realm['default_optional_client_scopes'] | default(omit) }}"
    default_roles: "{{ realm['default_roles'] | default(omit) }}"
    default_signature_algorithm: "{{ realm['default_signature_algorithm'] | default(omit) }}"
    direct_grant_flow: "{{ realm['direct_grant_flow'] | default(omit) }}"
    display_name: "{{ realm['display_name'] | default(omit) }}"
    display_name_html: "{{ realm['display_name_html'] | default(omit) }}"
    docker_authentication_flow: "{{ realm['docker_authentication_flow'] | default(omit) }}"
    duplicate_emails_allowed: "{{ realm['duplicate_emails_allowed'] | default(omit) }}"
    edit_username_allowed: "{{ realm['edit_username_allowed'] | default(omit) }}"
    email_theme: "{{ realm['email_theme'] | default(omit) }}"
    enabled: "{{ realm['enabled'] | default(omit) }}"
    enabled_event_types: "{{ realm['enabled_event_types'] | default(omit) }}"
    events_enabled: "{{ realm['events_enabled'] | default(omit) }}"
    events_expiration: "{{ realm['events_expiration'] | default(omit) }}"
    events_listeners: "{{ realm['events_listeners'] | default(omit) }}"
    failure_factor: "{{ realm['failure_factor'] | default(omit) }}"
    internationalization_enabled: "{{ realm['internationalization_enabled'] | default(omit) }}"
    login_theme: "{{ realm['login_theme'] | default(omit) }}"
    login_with_email_allowed: "{{ realm['login_with_email_allowed'] | default(omit) }}"
    max_delta_time_seconds: "{{ realm['max_delta_time_seconds'] | default(omit) }}"
    max_failure_wait_seconds: "{{ realm['max_failure_wait_seconds'] | default(omit) }}"
    minimum_quick_login_wait_seconds: "{{ realm['minimum_quick_login_wait_seconds'] | default(omit) }}"
    not_before: "{{ realm['not_before'] | default(omit) }}"
    offline_session_idle_timeout: "{{ realm['offline_session_idle_timeout'] | default(omit) }}"
    offline_session_max_lifespan: "{{ realm['offline_session_max_lifespan'] | default(omit) }}"
    offline_session_max_lifespan_enabled: "{{ realm['offline_session_max_lifespan_enabled'] | default(omit) }}"
    organizations_enabled: "{{ realm['organizations_enabled'] | default(omit) }}"
    otp_policy_algorithm: "{{ realm['otp_policy_algorithm'] | default(omit) }}"
    otp_policy_digits: "{{ realm['otp_policy_digits'] | default(omit) }}"
    otp_policy_initial_counter: "{{ realm['otp_policy_initial_counter'] | default(omit) }}"
    otp_policy_look_ahead_window: "{{ realm['otp_policy_look_ahead_window'] | default(omit) }}"
    otp_policy_period: "{{ realm['otp_policy_period'] | default(omit) }}"
    otp_policy_type: "{{ realm['otp_policy_type'] | default(omit) }}"
    otp_supported_applications: "{{ realm['otp_supported_applications'] | default(omit) }}"
    password_policy: "{{ realm['password_policy'] | default(omit) }}"
    permanent_lockout: "{{ realm['permanent_lockout'] | default(omit) }}"
    quick_login_check_milli_seconds: "{{ realm['quick_login_check_milli_seconds'] | default(omit) }}"
    refresh_token: "{{ realm['refresh_token'] | default(omit) }}"
    refresh_token_max_reuse: "{{ realm['refresh_token_max_reuse'] | default(omit) }}"
    registration_allowed: "{{ realm['registration_allowed'] | default(omit) }}"
    registration_email_as_username: "{{ realm['registration_email_as_username'] | default(omit) }}"
    registration_flow: "{{ realm['registration_flow'] | default(omit) }}"
    remember_me: "{{ realm['remember_me'] | default(omit) }}"
    reset_credentials_flow: "{{ realm['reset_credentials_flow'] | default(omit) }}"
    reset_password_allowed: "{{ realm['reset_password_allowed'] | default(omit) }}"
    revoke_refresh_token: "{{ realm['revoke_refresh_token'] | default(omit) }}"
    smtp_server: "{{ realm['smtp_server'] | default(omit) }}"
    ssl_required: "{{ realm['ssl_required'] | default(omit) }}"
    sso_session_idle_timeout: "{{ realm['sso_session_idle_timeout'] | default(omit) }}"
    sso_session_idle_timeout_remember_me: "{{ realm['sso_session_idle_timeout_remember_me'] | default(omit) }}"
    sso_session_max_lifespan: "{{ realm['sso_session_max_lifespan'] | default(omit) }}"
    sso_session_max_lifespan_remember_me: "{{ realm['sso_session_max_lifespan_remember_me'] | default(omit) }}"
    supported_locales: "{{ realm['supported_locales'] | default(omit) }}"
    user_managed_access_allowed: "{{ realm['user_managed_access_allowed'] | default(omit) }}"
    verify_email: "{{ realm['verify_email'] | default(omit) }}"
    state: "{{ realm['state'] | default('present') }}"
  loop: "{{ keycloak_realms }}"
  loop_control:
    loop_var: 'realm'
    label: "{{ realm['name'] }}"

- name: 'Ensure User Federation for realms'
  community.general.keycloak_user_federation:
    auth_keycloak_url: 'http://localhost:8080'
    auth_username: "{{ keycloak_admin_username }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: 'master'
    realm: "{{ federation['realm'] }}"
    name: "{{ federation['name'] }}"
    bind_credential_update_mode: "{{ federation['bind_credential_update_mode'] | default(omit) }}"
    config: "{{ federation['config'] | default(omit) }}"
    mappers: "{{ federation['mappers'] | default(omit) }}"
    provider_id: "{{ federation['provider_id'] | default(omit) }}"
    remove_unspecified_mappers: "{{ federation['remove_unspecified_mappers'] | default(omit) }}"
  loop: "{{ keycloak_user_federations }}"
  loop_control:
    loop_var: 'federation'
    label: "{{ federation['name'] }}"
