---
- name: 'Converge'
  hosts: 'all'
  vars:
    keycloak_podman_rootless: false
  tasks:
    - name: 'Run role'
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
